# These are supported funding model platforms

github: [brunokobi]        # ativa o botão "♥ Sponsor" no topo do repositório
patreon: #                 # single Patreon username
open_collective: #         # single Open Collective username
ko_fi: #                   # single Ko-fi username
tidelift: #                # e.g., npm/babel
community_bridge: #        # e.g., cloud-foundry
liberapay: #               # single Liberapay username
issuehunt: #               # single IssueHunt username
lfx_crowdfunding: #        # e.g., cloud-foundry
polar: #                   # single Polar username
buy_me_a_coffee: #         # single Buy Me a Coffee username
thanks_dev: #              # single thanks.dev username
custom: #                  # up to 4 custom URLs, e.g., ['https://...', 'https://...']
